// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include <thrift/protocol/TBinaryProtocol.h>

#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

#include "rsg/services.hpp"
#include "client/RsgClientEngine.hpp"
#include "rsg/actor.hpp"
#include "rsg/mailbox.hpp"
#include "rsg/host.hpp"

#include "xbt.h"
#include "simgrid/s4u.h"

#include <stdio.h>
#include <iostream>

#include "struct.h"

XBT_LOG_NEW_CATEGORY(RSG_THRIFT_CLIENT, "Remote SimGrid");
XBT_LOG_NEW_DEFAULT_SUBCATEGORY(RSG_THRIFT_REMOTE_SERVER, RSG_THRIFT_CLIENT , "RSG server (Remote SimGrid)");

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;
using namespace ::RsgService;

using namespace ::simgrid;

int main(int argc, char **argv) {
  rsg::Mailbox *mbox = rsg::Mailbox::byName("toto");
  char *received = rsg::this_actor::recv(*mbox);
  XBT_INFO("Received : %s with size of %d ", received, strlen(received) );
  
  int *recInt = (int*) rsg::this_actor::recv(*mbox);
  XBT_INFO("Received : %d ", *recInt);
  free(recInt);
  
  recInt = (int*) rsg::this_actor::recv(*mbox);
  XBT_INFO("Received : %d ", *recInt);
  
  int *recTabInt;
  recTabInt = (int*) rsg::this_actor::recv(*mbox);
  for(int i = 0; i < *recInt ;i++) {
    XBT_INFO(" tab[%d] = %d", i , recTabInt[i]);
  }
  free(recTabInt);
  free(recInt);
  
  structMsg *recStruct = (structMsg*) rsg::this_actor::recv(*mbox);
  XBT_INFO(" recStruct->intMsg = %d", recStruct->intMsg);
  XBT_INFO(" recStruct->msg = %s", recStruct->msg);
  free(recStruct);
  rsg::this_actor::quit();
  return 0;
}
