// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: rsg.proto

#include "rsg.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace protobuf_rsg_2eproto {
extern PROTOBUF_INTERNAL_EXPORT_protobuf_rsg_2eproto ::google::protobuf::internal::SCCInfo<0> scc_info_Command_AddActorCommand;
}  // namespace protobuf_rsg_2eproto
namespace rsg {
class Command_AddActorCommandDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Command_AddActorCommand>
      _instance;
} _Command_AddActorCommand_default_instance_;
class CommandDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Command>
      _instance;
  const ::rsg::Command_AddActorCommand* addactor_;
  bool start_;
  bool kill_;
  bool status_;
} _Command_default_instance_;
}  // namespace rsg
namespace protobuf_rsg_2eproto {
static void InitDefaultsCommand_AddActorCommand() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::rsg::_Command_AddActorCommand_default_instance_;
    new (ptr) ::rsg::Command_AddActorCommand();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::rsg::Command_AddActorCommand::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_Command_AddActorCommand =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsCommand_AddActorCommand}, {}};

static void InitDefaultsCommand() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::rsg::_Command_default_instance_;
    new (ptr) ::rsg::Command();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::rsg::Command::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<1> scc_info_Command =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 1, InitDefaultsCommand}, {
      &protobuf_rsg_2eproto::scc_info_Command_AddActorCommand.base,}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_Command_AddActorCommand.base);
  ::google::protobuf::internal::InitSCC(&scc_info_Command.base);
}

::google::protobuf::Metadata file_level_metadata[2];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::rsg::Command_AddActorCommand, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::rsg::Command_AddActorCommand, actorname_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::rsg::Command_AddActorCommand, hostname_),
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::rsg::Command, _internal_metadata_),
  ~0u,  // no _extensions_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::rsg::Command, _oneof_case_[0]),
  ~0u,  // no _weak_field_map_
  offsetof(::rsg::CommandDefaultTypeInternal, addactor_),
  offsetof(::rsg::CommandDefaultTypeInternal, start_),
  offsetof(::rsg::CommandDefaultTypeInternal, kill_),
  offsetof(::rsg::CommandDefaultTypeInternal, status_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::rsg::Command, type_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::rsg::Command_AddActorCommand)},
  { 7, -1, sizeof(::rsg::Command)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::rsg::_Command_AddActorCommand_default_instance_),
  reinterpret_cast<const ::google::protobuf::Message*>(&::rsg::_Command_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "rsg.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 2);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\trsg.proto\022\003rsg\"\256\001\n\007Command\0220\n\010addActor"
      "\030\001 \001(\0132\034.rsg.Command.AddActorCommandH\000\022\017"
      "\n\005start\030\002 \001(\010H\000\022\016\n\004kill\030\003 \001(\010H\000\022\020\n\006statu"
      "s\030\004 \001(\010H\000\0326\n\017AddActorCommand\022\021\n\tactorNam"
      "e\030\001 \001(\t\022\020\n\010hostName\030\002 \001(\tB\006\n\004typeb\006proto"
      "3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 201);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "rsg.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_rsg_2eproto
namespace rsg {

// ===================================================================

void Command_AddActorCommand::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Command_AddActorCommand::kActorNameFieldNumber;
const int Command_AddActorCommand::kHostNameFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Command_AddActorCommand::Command_AddActorCommand()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_rsg_2eproto::scc_info_Command_AddActorCommand.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:rsg.Command.AddActorCommand)
}
Command_AddActorCommand::Command_AddActorCommand(const Command_AddActorCommand& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  actorname_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.actorname().size() > 0) {
    actorname_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.actorname_);
  }
  hostname_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.hostname().size() > 0) {
    hostname_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.hostname_);
  }
  // @@protoc_insertion_point(copy_constructor:rsg.Command.AddActorCommand)
}

void Command_AddActorCommand::SharedCtor() {
  actorname_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  hostname_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

Command_AddActorCommand::~Command_AddActorCommand() {
  // @@protoc_insertion_point(destructor:rsg.Command.AddActorCommand)
  SharedDtor();
}

void Command_AddActorCommand::SharedDtor() {
  actorname_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  hostname_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void Command_AddActorCommand::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* Command_AddActorCommand::descriptor() {
  ::protobuf_rsg_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_rsg_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Command_AddActorCommand& Command_AddActorCommand::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_rsg_2eproto::scc_info_Command_AddActorCommand.base);
  return *internal_default_instance();
}


void Command_AddActorCommand::Clear() {
// @@protoc_insertion_point(message_clear_start:rsg.Command.AddActorCommand)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  actorname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  hostname_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool Command_AddActorCommand::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:rsg.Command.AddActorCommand)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string actorName = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_actorname()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->actorname().data(), static_cast<int>(this->actorname().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "rsg.Command.AddActorCommand.actorName"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // string hostName = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_hostname()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->hostname().data(), static_cast<int>(this->hostname().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "rsg.Command.AddActorCommand.hostName"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:rsg.Command.AddActorCommand)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:rsg.Command.AddActorCommand)
  return false;
#undef DO_
}

void Command_AddActorCommand::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:rsg.Command.AddActorCommand)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string actorName = 1;
  if (this->actorname().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->actorname().data(), static_cast<int>(this->actorname().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "rsg.Command.AddActorCommand.actorName");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->actorname(), output);
  }

  // string hostName = 2;
  if (this->hostname().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->hostname().data(), static_cast<int>(this->hostname().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "rsg.Command.AddActorCommand.hostName");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->hostname(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:rsg.Command.AddActorCommand)
}

::google::protobuf::uint8* Command_AddActorCommand::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:rsg.Command.AddActorCommand)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string actorName = 1;
  if (this->actorname().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->actorname().data(), static_cast<int>(this->actorname().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "rsg.Command.AddActorCommand.actorName");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->actorname(), target);
  }

  // string hostName = 2;
  if (this->hostname().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->hostname().data(), static_cast<int>(this->hostname().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "rsg.Command.AddActorCommand.hostName");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->hostname(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:rsg.Command.AddActorCommand)
  return target;
}

size_t Command_AddActorCommand::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:rsg.Command.AddActorCommand)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // string actorName = 1;
  if (this->actorname().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->actorname());
  }

  // string hostName = 2;
  if (this->hostname().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->hostname());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Command_AddActorCommand::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:rsg.Command.AddActorCommand)
  GOOGLE_DCHECK_NE(&from, this);
  const Command_AddActorCommand* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Command_AddActorCommand>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:rsg.Command.AddActorCommand)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:rsg.Command.AddActorCommand)
    MergeFrom(*source);
  }
}

void Command_AddActorCommand::MergeFrom(const Command_AddActorCommand& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:rsg.Command.AddActorCommand)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  if (from.actorname().size() > 0) {

    actorname_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.actorname_);
  }
  if (from.hostname().size() > 0) {

    hostname_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.hostname_);
  }
}

void Command_AddActorCommand::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:rsg.Command.AddActorCommand)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Command_AddActorCommand::CopyFrom(const Command_AddActorCommand& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:rsg.Command.AddActorCommand)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Command_AddActorCommand::IsInitialized() const {
  return true;
}

void Command_AddActorCommand::Swap(Command_AddActorCommand* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Command_AddActorCommand::InternalSwap(Command_AddActorCommand* other) {
  using std::swap;
  actorname_.Swap(&other->actorname_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  hostname_.Swap(&other->hostname_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata Command_AddActorCommand::GetMetadata() const {
  protobuf_rsg_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_rsg_2eproto::file_level_metadata[kIndexInFileMessages];
}


// ===================================================================

void Command::InitAsDefaultInstance() {
  ::rsg::_Command_default_instance_.addactor_ = const_cast< ::rsg::Command_AddActorCommand*>(
      ::rsg::Command_AddActorCommand::internal_default_instance());
  ::rsg::_Command_default_instance_.start_ = false;
  ::rsg::_Command_default_instance_.kill_ = false;
  ::rsg::_Command_default_instance_.status_ = false;
}
void Command::set_allocated_addactor(::rsg::Command_AddActorCommand* addactor) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  clear_type();
  if (addactor) {
    ::google::protobuf::Arena* submessage_arena = NULL;
    if (message_arena != submessage_arena) {
      addactor = ::google::protobuf::internal::GetOwnedMessage(
          message_arena, addactor, submessage_arena);
    }
    set_has_addactor();
    type_.addactor_ = addactor;
  }
  // @@protoc_insertion_point(field_set_allocated:rsg.Command.addActor)
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Command::kAddActorFieldNumber;
const int Command::kStartFieldNumber;
const int Command::kKillFieldNumber;
const int Command::kStatusFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Command::Command()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_rsg_2eproto::scc_info_Command.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:rsg.Command)
}
Command::Command(const Command& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  clear_has_type();
  switch (from.type_case()) {
    case kAddActor: {
      mutable_addactor()->::rsg::Command_AddActorCommand::MergeFrom(from.addactor());
      break;
    }
    case kStart: {
      set_start(from.start());
      break;
    }
    case kKill: {
      set_kill(from.kill());
      break;
    }
    case kStatus: {
      set_status(from.status());
      break;
    }
    case TYPE_NOT_SET: {
      break;
    }
  }
  // @@protoc_insertion_point(copy_constructor:rsg.Command)
}

void Command::SharedCtor() {
  clear_has_type();
}

Command::~Command() {
  // @@protoc_insertion_point(destructor:rsg.Command)
  SharedDtor();
}

void Command::SharedDtor() {
  if (has_type()) {
    clear_type();
  }
}

void Command::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* Command::descriptor() {
  ::protobuf_rsg_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_rsg_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Command& Command::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_rsg_2eproto::scc_info_Command.base);
  return *internal_default_instance();
}


void Command::clear_type() {
// @@protoc_insertion_point(one_of_clear_start:rsg.Command)
  switch (type_case()) {
    case kAddActor: {
      delete type_.addactor_;
      break;
    }
    case kStart: {
      // No need to clear
      break;
    }
    case kKill: {
      // No need to clear
      break;
    }
    case kStatus: {
      // No need to clear
      break;
    }
    case TYPE_NOT_SET: {
      break;
    }
  }
  _oneof_case_[0] = TYPE_NOT_SET;
}


void Command::Clear() {
// @@protoc_insertion_point(message_clear_start:rsg.Command)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  clear_type();
  _internal_metadata_.Clear();
}

bool Command::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:rsg.Command)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // .rsg.Command.AddActorCommand addActor = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessage(
               input, mutable_addactor()));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool start = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(16u /* 16 & 0xFF */)) {
          clear_type();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &type_.start_)));
          set_has_start();
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool kill = 3;
      case 3: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(24u /* 24 & 0xFF */)) {
          clear_type();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &type_.kill_)));
          set_has_kill();
        } else {
          goto handle_unusual;
        }
        break;
      }

      // bool status = 4;
      case 4: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(32u /* 32 & 0xFF */)) {
          clear_type();
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   bool, ::google::protobuf::internal::WireFormatLite::TYPE_BOOL>(
                 input, &type_.status_)));
          set_has_status();
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:rsg.Command)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:rsg.Command)
  return false;
#undef DO_
}

void Command::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:rsg.Command)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .rsg.Command.AddActorCommand addActor = 1;
  if (has_addactor()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->_internal_addactor(), output);
  }

  // bool start = 2;
  if (has_start()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(2, this->start(), output);
  }

  // bool kill = 3;
  if (has_kill()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(3, this->kill(), output);
  }

  // bool status = 4;
  if (has_status()) {
    ::google::protobuf::internal::WireFormatLite::WriteBool(4, this->status(), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:rsg.Command)
}

::google::protobuf::uint8* Command::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:rsg.Command)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // .rsg.Command.AddActorCommand addActor = 1;
  if (has_addactor()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageToArray(
        1, this->_internal_addactor(), deterministic, target);
  }

  // bool start = 2;
  if (has_start()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(2, this->start(), target);
  }

  // bool kill = 3;
  if (has_kill()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(3, this->kill(), target);
  }

  // bool status = 4;
  if (has_status()) {
    target = ::google::protobuf::internal::WireFormatLite::WriteBoolToArray(4, this->status(), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:rsg.Command)
  return target;
}

size_t Command::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:rsg.Command)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  switch (type_case()) {
    // .rsg.Command.AddActorCommand addActor = 1;
    case kAddActor: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSize(
          *type_.addactor_);
      break;
    }
    // bool start = 2;
    case kStart: {
      total_size += 1 + 1;
      break;
    }
    // bool kill = 3;
    case kKill: {
      total_size += 1 + 1;
      break;
    }
    // bool status = 4;
    case kStatus: {
      total_size += 1 + 1;
      break;
    }
    case TYPE_NOT_SET: {
      break;
    }
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Command::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:rsg.Command)
  GOOGLE_DCHECK_NE(&from, this);
  const Command* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Command>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:rsg.Command)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:rsg.Command)
    MergeFrom(*source);
  }
}

void Command::MergeFrom(const Command& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:rsg.Command)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  switch (from.type_case()) {
    case kAddActor: {
      mutable_addactor()->::rsg::Command_AddActorCommand::MergeFrom(from.addactor());
      break;
    }
    case kStart: {
      set_start(from.start());
      break;
    }
    case kKill: {
      set_kill(from.kill());
      break;
    }
    case kStatus: {
      set_status(from.status());
      break;
    }
    case TYPE_NOT_SET: {
      break;
    }
  }
}

void Command::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:rsg.Command)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Command::CopyFrom(const Command& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:rsg.Command)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Command::IsInitialized() const {
  return true;
}

void Command::Swap(Command* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Command::InternalSwap(Command* other) {
  using std::swap;
  swap(type_, other->type_);
  swap(_oneof_case_[0], other->_oneof_case_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata Command::GetMetadata() const {
  protobuf_rsg_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_rsg_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace rsg
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::rsg::Command_AddActorCommand* Arena::CreateMaybeMessage< ::rsg::Command_AddActorCommand >(Arena* arena) {
  return Arena::CreateInternal< ::rsg::Command_AddActorCommand >(arena);
}
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::rsg::Command* Arena::CreateMaybeMessage< ::rsg::Command >(Arena* arena) {
  return Arena::CreateInternal< ::rsg::Command >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
