// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "rsg/actor.hpp"
#include "rsg/mailbox.hpp"
#include "rsg/host.hpp"

#include "../print.hpp"

using namespace ::simgrid;

int main() {
  RSG_INFO("hello from server");

  rsg::HostPtr host = rsg::Host::current();

  RSG_INFO("Hostname current Peak : %f",  host->currentPowerPeak());

  RSG_INFO("hostname : %s", rsg::Host::current()->getName().c_str());

  RSG_INFO("core count : %d", host->coreCount());
  RSG_INFO("state count %d", host->pstatesCount());
  RSG_INFO("state -> %d", host->pstate());

  rsg::this_actor::quit();
  return 0;
}
