// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include <thrift/protocol/TBinaryProtocol.h>

#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

#include "rsg/RsgServiceImpl.h"
#include "client/RsgClientEngine.hpp"
#include "rsg/actor.hpp"
#include "rsg/mailbox.hpp"
#include "rsg/host.hpp"

#include "xbt.h"
#include "simgrid/s4u.h"

#include <iostream>

XBT_LOG_NEW_CATEGORY(RSG_THRIFT_CLIENT, "Remote SimGrid");
XBT_LOG_NEW_DEFAULT_SUBCATEGORY(RSG_THRIFT_REMOTE_SERVER, RSG_THRIFT_CLIENT , "RSG server (Remote SimGrid)");

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;
using namespace ::RsgService;

int main(int argc, char **argv) {

  XBT_INFO("hello from server");

  rsg::Mailbox *mbox = rsg::Mailbox::byName("toto");
  rsg::Actor &self = rsg::Actor::self();
  rsg::Host &host = rsg::Host::current();
  self.setAutoRestart(true);

  XBT_INFO("Hostname current Peak : %f",  host.currentPowerPeak());
  XBT_INFO("Hostname current Peak : %f",  host.powerPeakAt(0));

  XBT_INFO("hostname : %s", rsg::Host::current().name().c_str());

  XBT_INFO("Received from client : %s", self.recv(*mbox));
  XBT_INFO("core count : %d", host.core_count());
  XBT_INFO("state count %d ", host.pstatesCount());
  XBT_INFO("state -> %d ", host.pstate());
  XBT_INFO("actor name -> %s", self.getName());
  XBT_INFO("actor pid -> %d", self.getPid());
  XBT_INFO("host name accessing by actor -> %s", self.getHost()->name().c_str());
  XBT_INFO("get kill time -> %d " , self.getKillTime());
  self.quit();
  return 0;
}
